name: Running Playwright Tests with Allure and MPT Reporting   
on: [push] 

permissions:
  id-token: write
  contents: write
      
jobs: 
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
                  
      - name: Get resource group with Azure CLI
        run: az group list

      - name: Install vsts
        run: npm install -g vsts-npm-auth

      - name: Use .npmrc   
        uses: bduff9/use-npmrc@v1.2
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install npm packages
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Azure PSDT Feed         
        run: |
          echo "Y" | npm init -y @azure/microsoft-playwright-testing-private-preview

      - name: Run Playwright tests        
        run: npx playwright test -c playwright.service.config.ts --reporter=allure-playwright
        env:
            PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: main
          path: allure_report_test

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: allure_report_test
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: allure-history
          destination_dir: docs/allure-report
      - uses: actions/upload-artifact@v4  
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30   
